//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;

public class Journee
{
    public List<Activite> _listeActivites {
        get;
        set;
    }

	public int _numero
	{
		get;
		set;
	}

	public virtual string _compteRendu
	{
		get;
		set;
	}


	public Journee(int numero, string compteRendu, string cheminPlanningXML)
	{
        _listeActivites = new List<Activite>();
        _numero = numero;
        _compteRendu = compteRendu;

        // Récupération de la liste des activités de la journée
        XDocument planningXML = XDocument.Load(cheminPlanningXML);
        var activites = from activite in _planningXML.Descendants("Activites") select activite;
        foreach (XElement a in activites.Elements("Activite"))
        {
            string nom = a.Element("NomAct").Value;
            DateTime debutAct = DateTime.Parce(a.Element("DebutAct").Value);
            DateTime finAct = DateTime.Parce(a.Element("FinAct").Value);
            bool ext = bool.Parse(a.Element("BoolExt").Value);
            string description = a.Element("DescriptionAct").Value;
            _listeActivites.Add(new Journee(num, cr, cheminXMLPlanning));
        }
	}

}

