//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Journee
{
    public List<Activite> _listeActivites {
        get;
        set;
    }

	public int _numero
	{
		get;
		set;
	}

	public virtual string _compteRendu
	{
		get;
		set;
	}


	public Journee(int numero, string compteRendu)
	{
        _listeActivites = new List<Activite>();
        _numero = numero;
        _compteRendu = compteRendu;
	}

}

