//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Linq;

public class Planning
{
    public virtual List<Journee> tableauJournees {
        get;
        set;
    }


	public virtual string _nomPlanning
	{
		get;
		set;
	}

	public virtual void majJourJXML(int nouveauJour)
	{
		throw new System.NotImplementedException();
	}

	public Planning(string nomPlanning, List<Journee> listJournees)
	{
        // ??
	}

    // Création de l'instance Planning à partir d'un fichier XML 
    public Planning (int DureeMission, string cheminXMLPlanning)
    {
        XDocument _planningXML = XDocument.Load(cheminXMLPlanning);
        //var jour = from jour in _planningXML.Descendants("Planning") select jour;
        //foreach (XElement j in planning.Elements("Jour"))
        //{
        //    string nomAstronaute = a.Value;
        //    _astronautes.Add(new Astronaute(nomAstronaute));
        //}
    }

}

